# Invalid CnfCertificationSuiteRun for testing purposes.
# Invalidation reason: preflightSecretName is an empty string.

apiVersion: cnf-certifications.redhat.com/v1alpha1
kind: CnfCertificationSuiteRun
metadata:
  labels:
    app.kubernetes.io/name: cnfcertificationsuiterun
    app.kubernetes.io/instance: cnfcertificationsuiterun-sample
    app.kubernetes.io/part-of: cnf-certsuite-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cnf-certsuite-operator
  name: cnfcertificationsuiterun-sample6
  namespace: cnf-certsuite-operator
spec:
  # TODO(user): Add fields here
  labelsFilter: "observability"
  logLevel: "info"
  timeout: "2h"

  configMapName: "cnf-certsuite-config"
  preflightSecretName : ""