apiVersion: v1
kind: Secret
metadata:
  name: cnf-certsuite-preflight-dockerconfig
  namespace: cnf-certsuite-operator
type: Opaque
data:
  # Sample of empty content, base64-coded: '{ "auths": {} }'
  preflight_dockerconfig.json: |
    eyAiYXV0aHMiOiB7fSB9Cg==
