apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: cnfcertificationsuiteruns.cnf-certifications.redhat.com
spec:
  conversion:
    strategy: None
  group: cnf-certifications.redhat.com
  names:
    kind: CnfCertificationSuiteRun
    listKind: CnfCertificationSuiteRunList
    plural: cnfcertificationsuiteruns
    singular: cnfcertificationsuiterun
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: CnfCertificationSuiteRun current status
      jsonPath: .status.phase
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CnfCertificationSuiteRun is the Schema for the cnfcertificationsuiteruns
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CnfCertificationSuiteRunSpec defines the desired state of
              CnfCertificationSuiteRun
            properties:
              configMapName:
                description: ConfigMapName holds the cnf certification suite yaml
                  config.
                type: string
              enableDataCollection:
                description: EnableDataCollection is set to true for enabling data
                  collection to collector
                type: boolean
              labelsFilter:
                description: LabelsFilter holds the labels filter/expression of the
                  test cases we want to run.
                type: string
              logLevel:
                description: LogLevel sets the CNF Certification Suite log level (TNF_LOG_LEVEL)
                type: string
              preflightSecretName:
                description: PreflightSecretName holds the secret name for preflight's
                  dockerconfig.
                type: string
              timeout:
                description: Total timeout for the CNF Cert Suite to run.
                type: string
            required:
            - configMapName
            - labelsFilter
            - logLevel
            - timeout
            type: object
          status:
            description: CnfCertificationSuiteRunStatus defines the observed state
              of CnfCertificationSuiteRun
            properties:
              cnfCertSuitePodName:
                description: CnfCertSuitePodName holds the name of the pod where the
                  CNF Certification Suite app is running.
                type: string
              phase:
                description: Phase holds the current phase of the CNF Certification
                  Suite run.
                enum:
                - CertSuiteDeploying
                - CertSuiteDeployFailure
                - CertSuiteRunning
                - CertSuiteFinished
                - CertSuiteError
                type: string
              report:
                description: Report holds the results and information related to the
                  CNF Certification Suite run.
                properties:
                  cnfCertSuiteVersion:
                    type: string
                  cnfTargets:
                    properties:
                      crds:
                        items:
                          type: string
                        type: array
                      csvs:
                        items:
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                          type: object
                        type: array
                      deployments:
                        items:
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                          type: object
                        type: array
                      helmChartReleases:
                        items:
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                          type: object
                        type: array
                      namespaces:
                        items:
                          type: string
                        type: array
                      nodes:
                        items:
                          type: string
                        type: array
                      pods:
                        items:
                          properties:
                            containers:
                              items:
                                type: string
                              type: array
                            name:
                              type: string
                            namespace:
                              type: string
                          type: object
                        type: array
                      services:
                        items:
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                          type: object
                        type: array
                      statefulSets:
                        items:
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                          type: object
                        type: array
                    type: object
                  ocpVersion:
                    type: string
                  results:
                    items:
                      description: TestCaseResult holds a test case result
                      properties:
                        logs:
                          type: string
                        reason:
                          type: string
                        result:
                          type: string
                        testCaseName:
                          type: string
                      required:
                      - result
                      - testCaseName
                      type: object
                    type: array
                  summary:
                    properties:
                      errored:
                        type: integer
                      failed:
                        type: integer
                      passed:
                        type: integer
                      skipped:
                        type: integer
                      total:
                        type: integer
                    required:
                    - errored
                    - failed
                    - passed
                    - skipped
                    - total
                    type: object
                  verdict:
                    type: string
                required:
                - cnfCertSuiteVersion
                - ocpVersion
                - results
                - summary
                - verdict
                type: object
            required:
            - phase
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
