apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cnf-certsuite-operator
  namespace: cnf-certsuite-operator
spec:
  sourceNamespace: cnf-certsuite-operator
  channel: alpha
  name: cnf-certsuite-operator
  source: cnf-certsuite-operator-olm-catalog
